### ISSUE TITLE
Should we include MatCL?

### ISSUE THREAD

**Issue by ranocha** [MuMPlaCL/ConservationLaws#13]
Currently, the compiled binaries `cl_get_devices.mexa64` and `cl_run_kernel.mexa64` are included in `matlab/`. There may be several options:
- We leave it as it is.
- We use [MatCL](https://github.com/MuMPlaCL/MatCL) and tell the user to add this dependency to Matlab's load path (as currently described in the README).
- We ship binaries for Linux and other systems such as Windows. However, adding binaries to git is not really optimal.

Any thoughts, @Kostaszki, @philipheinisch?

**Comment by philipheinisch** [comment]
I would suggest removing the MatCL binaries and instead just reference the MatCL repository. We could add a set of precompiled binaries to MatCL, so if any user just wants the binaries without setting up the build system, it is possible to download them from the central MatCL repository.
